title: IMS322 Docs
description: Stuff for IMS322
theme: just-the-docs
# color_scheme: dark

$link-color: $blue-100;

url: https://sheffield-miami-fall2023.github.io/IMS322-docs/

aux_links:
  # Template Repository: https://github.com/just-the-docs/just-the-docs-template